version: '3'

services:
  javaapp:
    image: mixaverross88/dockerize_java_mysql_example_project
    ports:
      - 80:8080
    networks:
      - isolated
    volumes:
      - /$(pwd):/usr/local/tomcat/webapps
  mysqlapp:
    image: mixaverross88/dockerize_java_mysql_example_project_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret 
    ports:
      - 3311:3306
    networks:
      - isolated

networks: 
  isolated:
    driver: bridge
    
